#!/usr/bin/env bash
set -eu

domain=keepers.chainlink-demo.app
yarn_project="$GITHUB_WORKSPACE/batch-nft-reveal/app"
repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
source_branch="feature/batch-nft-app"
target_branch="gh-pages"
build_dir="/tmp/dist"
short_hash="$(git rev-parse --short=8 HEAD)"
short_subject="$(git log -1 --pretty=format:'%s')"
current_action_url="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
br="
"

# configure github username/e-mail and fetch source branch
cd "$GITHUB_WORKSPACE"
git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"
git fetch
git checkout "$source_branch"

# build yarn project
cd $yarn_project
yarn install
yarn build
yarn export -o "$build_dir"

# checkout/create $target_branch
git checkout -fB "$target_branch"

mv ../../.git "$build_dir"
cd "$build_dir"
touch .nojekyll

# create CNAME if $domain is set
[ "${domain}" ] && echo -n "$domain" > CNAME
echo "[![Deploy to GitHub Pages](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/gh-pages.yml/badge.svg)](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/gh-pages.yml)" > README.md

git add .
git commit -m "⚙️ rebuild ${short_hash} [${short_subject}]${br}${br}${current_action_url}"

if [ $? -ne 0 ]; then
    echo "nothing to commit"
    exit 0
fi

git remote set-url origin "$repo_uri"
git push -f origin "$target_branch"

